---
restylers:
  - astyle
  - autopep8
  - black
  - dfmt
  - elm-format
  - hindent
  # TODO: Blows up because of pom.xml
  # - jdt
  - pg_format
  - php-cs-fixer
  - prettier
  - prettier-markdown
  - prettier-ruby
  - prettier-yaml
  - reorder-python-imports
  - rubocop
  - rustfmt
  - shellharden
  - shfmt
  - terraform
  - yapf

  # Non-default, need to be limited to not conflict
  - brittany:
      include:
        - new-files/patterns.hs
  - stylish-haskell:
      include:
        - new-files/case.hs
        - new-files/case-2.hs

  - hlint:
      include:
        - new-files/redundant-dollar.hs
  - google-java-format:
      include:
        - new-files/Enum.java

  - rustfmt:
      include:
        - '!new-files/bug.rs'
